artifact_uri: file://root/hardik/mlflow_demo/model_data/0/ff0961b8ebb64cd994675d1c8ccf75b2/artifacts
end_time: 1605616662489
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ff0961b8ebb64cd994675d1c8ccf75b2
run_uuid: ff0961b8ebb64cd994675d1c8ccf75b2
source_name: ''
source_type: 4
source_version: ''
start_time: 1605616661614
status: 3
tags: []
user_id: root
